frontend:
  image:
    repository: mehdiboutoumit/tutorials-app
    tag: angular-frontend
  service:
    name: frontend-service
    port: 8081
service:
  port: 8081

backend:
  image:
    repository: mehdiboutoumit/tutorials-app
    tag: spring-backend
  service:
    name: backend-service
    port: 8080
serviceAccount:
  create: false

mysql:
  statefulset:
    name: mysql-statefulset
  image:
    repository: mysql
    tag: latest
  rootPassword: root
  database: testdb
  secret:
    name: mysql-secret
  configMap:
    name: mysql-conf

ingress:
  enabled: false  # ou true selon vos besoins
  className: "nginx"  # spécifiez la classe d'ingress que vous utilisez
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    
  hosts:
    - host: mehdi-aseds-ine2-exam.com 
      paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8080
autoscaling:
  enabled: false

annotations:
  service: {}


