{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tutorials-app-chart.serviceAccountName" . }}
 
 
  automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
